# Generated by Django 4.0.5 on 2022-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0)),
                ('s_h_min', models.SmallIntegerField()),
                ('s_h_max', models.SmallIntegerField()),
                ('s_w_min', models.SmallIntegerField()),
                ('s_w_max', models.SmallIntegerField()),
                ('w_h_min', models.SmallIntegerField()),
                ('w_h_max', models.SmallIntegerField()),
                ('w_w_min', models.SmallIntegerField()),
                ('w_w_max', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='eegcheck',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eegcheck',
            name='error',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
