# Generated by Django 4.0.5 on 2022-06-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings_alter_eegcheck_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegcheck',
            name='has_patterns',
            field=models.BooleanField(default=False),
        ),
    ]
