# Generated by Django 4.0.5 on 2022-06-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eegcheck_has_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegcheck',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.settings'),
        ),
    ]
